version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: labeler
      POSTGRES_USER: labeler
      POSTGRES_DB: labeler
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labeler"]
      interval: 10s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
  minio-console:
    image: minio/console:latest
    environment:
      MINIO_SERVER: http://minio:9000
      MINIO_SERVER_ACCESS_KEY: minioadmin
      MINIO_SERVER_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/login"]
      interval: 10s
      retries: 5
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
    volumes:
      - .:/app
  worker:
    build: .
    command: celery -A worker.main worker --loglevel=info
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "celery -A worker.main inspect ping -t 1 > /dev/null"]
      interval: 10s
      retries: 5
    volumes:
      - .:/app
volumes:
  postgres-data:
  redis-data:
  minio-data:
