version: "3.9"
services:
  gen:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    device_requests:
      - driver: nvidia
        count: 1
        capabilities: ["gpu"]

